### ISSUE TITLE
blocked by CORS policy: No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by Kaplas85** [adrianolmedo/bcvcurs#12]
Llevo usando la API un tiempo pero esta genera un error (aunque el servidor de Heroku esté corriendo) con un error 503. Anexo captura del resultado en consola y el codigo que estoy usando.

Error en consola
![image](https://user-images.githubusercontent.com/53917815/159174472-6c4a7878-9719-4f11-8af0-7a6b661b3041.png)

Codigo para obtener los datos
![image](https://user-images.githubusercontent.com/53917815/159174499-1c5a5458-f6d7-40ae-888d-3fedcc273c1e.png)

**Comment by adrianolmedo** [comment]
Al parecer había un problema con el sitio web del banco, ya volví a probar y está todo bien. Avísame de nuevo.

**Comment by Kaplas85** [comment]
El error todavía está
![image](https://user-images.githubusercontent.com/53917815/159279693-4fd565be-e620-4010-885f-58d50095d292.png)

Los CORS normalmente dan en backend. No se mucho de Go pero al configuración para este tipo de los CORS es permitir todos los origenes, que ese pareciera ser el problema.

**Comment by adrianolmedo** [comment]
Al parecer está habilitado CORS, que raro eso suceda: https://github.com/adrianolmedo/bcvcurs/blob/003970dbf2349c271141fd12504b79ba1de09412/response.go#L77

Sólo hice pruebas con fetch, no con axios. Estaré también haciendo unas actualizaciones para implementar caché y no haya mucha fricción contra el servidor http://bcv.org.ve.

**Comment by Kaplas85** [comment]
Yo empecé usando Fetch y posteriormente cambié a Axios creyendo que el problema podría venir por ahí. Me parece que el error es porque estoy haciendo peticiones desde un localhost y siempre es así porque los hace desde una app en electron.
